name: Firebase Deploy

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the main branch. Change "main" if your branch is named differently.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      run: firebase deploy --only hosting
